import { test, expect } from '@playwright/test';

// page is argument, first page of browser to start tests
// for every await, use async

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.getByText('Forms').click()
  await page.getByText('Form Layouts').click()
})

test('Locator syntax rules', async ({ page }) => {
  //By tagname
   await page.locator('input').first().click()

    //By ID
    page.locator('#inputEmail')

    //By class
    page.locator('.shape-rectangle')

    //By attribute
    page.locator('[placeholder="Email"]')

    //By class value full
    page.locator('[class="input-full-width size-medium status-basic shape-rectangle nb-transition"]')

    //By combining diff selector
    page.locator('input [placeholder="Email"] [nbinput]')

    //By xpath not recommended
    page.locator('//*[@id="inputEmail1"]')

    //By partial text
    page.locator(':text("Using")')

    //By exact text match
    page.locator(':text-is("Using the grid")')
})

test('User facing locators', async({page})=>{
    await page.getByRole('textbox',{name:"Email"}).first().click()
    await page.getByRole('button',{name:"Sign in"}).first().click()
    await page.getByLabel('Email').first().click()
    await page.getByPlaceholder('Jane Doe').click()
    await page.getByText('Using the Grid').click()
    //await page.getByTitle('IoT Dashboard').click()

    //data-test id can be generated by user in html and used in  test
    await page.getByTestId('SignIn').click

})

test('locating child elements', async({page})=>{
    //parent nb-card to child radio button option 1
    await page.locator('nb-card nb-radio :text-is("Option 1")').click()
   //as above you can use with locator 
    await page.locator('nb-card').locator('nb-radio').locator(':text-is("Option 2")').click()

    await page.locator('nb-card').getByRole('button',{name : "Sign in"}).first().click()
    //using nth child index frame
    await page.locator('nb-card').nth(3).getByRole('button').click()
})


test('locating parent elements from child', async({page})=>{
    await page.locator('nb-card',{hasText : "Using the Grid"}).getByRole('textbox',{name:"Email"}).click()
    await page.locator('nb-card', {has: page.locator('#inputEmail1')}).getByRole('textbox',{name :"Email"}).click()

    await page.locator('nb-card').filter({hasText:"Basic form"}).getByRole('textbox',{name:"Email"}).click()
    await page.locator('nb-card').filter({has:page.locator('.status-danger')}).getByRole('textbox',{name :"Password"}).click()

    await page.locator('nb-card').filter({has:page.locator('nb-checkbox')}).filter({hasText:"Sign in"})
    .getByRole('textbox', {name :"Email"}).click()

    // one level up parent using ..
    await page.locator(':text-is("Using the Grid")').locator('..').getByRole('textbox',{name : "Email"}).click()


})


test('Reusing the locators', async({page})=>{

    //using const instead of page.locator('nb-card').filter({hasText:"Basic form"})
    //using emailField instead of basicForm.getByRole('textbox',{name:"Email"})
  const basicForm=page.locator('nb-card').filter({hasText:"Basic form"})
  const emailField=basicForm.getByRole('textbox',{name:"Email"})



    await emailField.fill("test@test.com")
    await basicForm.getByRole('textbox',{name:"Password"}).fill("Welcome123")
    await basicForm.locator('nb-checkbox').click()
    await basicForm.getByRole('button').click()

    //asertion use expect, in order to use expect import above 

    await expect(emailField).toHaveValue('test@test.com')
})


test('extracting values', async({page})=>{
    //single text value of button using textContent
const basicForm=page.locator('nb-card').filter({hasText:"Basic form"})
const buttonText=await basicForm.locator('button').textContent()
expect (buttonText).toEqual('Submit')

//all text values of radio button form frame 1 using allTextContents
const allRadioButtonLabels= await page.locator('nb-radio').allTextContents()
expect(allRadioButtonLabels).toContain("Option 1")

//input value of textfield like email test@test.com use inputValue
const emailField= basicForm.getByRole('textbox',{name : "Email"})
await emailField.fill('test@test.com')     
const emailValue= await emailField.inputValue()
expect (emailValue).toEqual('test@test.com')

//placeholder getAttribute
const placeholderValue= await emailField.getAttribute('placeholder')

})


test('assertions',async({page})=>{
    //general assertion
    const value=5
    expect(value).toEqual(5)

 const basiFormButton= page.locator('nb-card').filter({hasText:"Basic form"}).locator('button')
 const text = await basiFormButton.textContent()
 expect(text).toEqual("Submit")

 // Locator assertion always use await(5 Secs wait)

 await expect(basiFormButton).toHaveText('Submit')

 // Soft Assertion

 await expect.soft(basiFormButton).toHaveText('Submit')
 await basiFormButton.click()

})

